config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :show, :index] do
    resources :goals, only: :index
  end

  resources :goals, except: :index

  resource :session, only: [:new, :create, :destroy]


end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  title      :string           not null
#  details    :text             not null
#  private    :boolean          default(FALSE), not null
#  completed  :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base

  belongs_to :user

  validates :user, :title, :details, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  has_many :goals

  validates :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :name, uniqueness: true, presence: true

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(name, password)
    user = User.find_by_name(name)
    user && user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def log_in(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    @current_user = user
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_out
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def index
    user = User.find(params[:user_id])
    @goals = user.goals
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to user_goals_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    flash[:errors] = @goal.errors.full_messages
    redirect_to goal_url(@goal)
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :details, :private, :completed)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create
    user = User.find_by_credentials(params[:user][:name], params[:user][:password])
    if user
      log_in(user)
      redirect_to user_goals_url(user)
    else
      flash[:errors] += ["Wrong credentials!!!!!!"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to user_goals_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form class="" action="/goals" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <input type="hidden" name="_method" value="patch">

  <label>
    Title
    <input type="text" name="goal[title]" value="<%=@goal.title %>">
  </label>
<br>
  <label>
    Details
    <textarea name="goal[details]" rows="8" cols="40"><%=@goal.details %></textarea>
  </label>

<br>

  <label >Private goal?</label>
  <input id="private_true" type="radio" name="goal[private]" value="true">
  <label for="private_true">True</label>
  <input id="private_false" type="radio" name="goal[private]" value="false" <%="checked"%>  >
  <label for="private_false">False</label>

</br>

  <label for="completion">Completed?</label>
  <select id="completion" name="goal[completed]">
    <option  value=""></option>
    <option  value="true">True</option>
    <option <%="selected"%>  value="false" >False</option>
  </select>

  <input type="submit" value="Submit Goal!!!">
</form>

app/views/goals/index.html.erb
<h1>Goals</h1>

<% @goals.each do |goal| %>
  <% if goal.private %>
    <% if logged_in? && current_user.id == goal.user_id%>
      <%= link_to goal.title, goal_url(goal) %>
    <% end %>
  <% else %>
    <%= link_to goal.title, goal_url(goal) %>
  <% end %>

<% end %>

app/views/goals/new.html.erb
<h1>New Goal</h1>

<form class="" action="/goals" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type="text" name="goal[title]" value="">
  </label>
<br>
  <label>
    Details
    <textarea name="goal[details]" rows="8" cols="40"></textarea>
  </label>

<br>

  <label >Private goal?</label>
  <input id="private_true" type="radio" name="goal[private]" value="true">
  <label for="private_true">True</label>
  <input id="private_false" type="radio" name="goal[private]" value="false">
  <label for="private_false">False</label>

</br>

  <label for="completion">Completed?</label>
  <select id="completion" name="goal[completed]">
    <option value=""></option>
    <option value="true">True</option>
    <option value="false">False</option>
  </select>

  <input type="submit" value="Submit Goal!!!">
</form>

app/views/goals/show.html.erb
<%= @goal.title %>
<%= @goal.details %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if logged_in? %>
    <%= current_user.name %>
    <%= button_to "Log Out", session_url, method: :delete %>
  <% else %>
    <%= link_to "Log In", new_session_url %>
  <% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>

<form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%=form_authenticity_token%>">

  <label>Name
    <input id="user_name" type="text" name="user[name]" value="">
  </label>

  <label for="user_password">Password</label>

  <input id="user_password" type="text" name="user[password]" value="">

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<%= @user.name %>
<%= link_to "User's goals", user_goals_url(@user) %>